@Service_HostAddress = http://localhost:5146
@Service_SkillBaseUrl = {{Service_HostAddress}}/experience/skill
@Token = some_faulty_token (use real token from webpage)

POST {{Service_SkillBaseUrl}}
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "name": "C++"
}

###

GET {{Service_SkillBaseUrl}}
Accept: application/json

###

@Skill_Id = 0

GET {{Service_SkillBaseUrl}}/{{Skill_Id}}
Accept: application/json