@Service_HostAddress = http://localhost:5146
@Service_SkillBaseUrl = {{Service_HostAddress}}/experience/skill
@Token = faultyToken (replace with real one from site)

POST {{Service_SkillBaseUrl}}
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "name": "C++"
}

###

GET {{Service_SkillBaseUrl}}
Accept: application/json

###

@Skill_Id = 15

GET {{Service_SkillBaseUrl}}/{{Skill_Id}}
Accept: application/json